trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)
  
# Please use Node.js version greater than 18.0 for succussful CI test.
# TO: Multiple version CI testing
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile checker-framework-vscode"
    yarn && yarn compile
    # Don't have the echo below, as it masks a failure from the yarn commands.
    # echo ">>> Compiled checker-framework-vscode"
    #    cd sample
    #    echo ">>> Run sample integration test"
    #    yarn && yarn compile && yarn test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'
